/* eslint-env node */
module.exports = {
    extends: [
        'eslint-config-eser',
    ].map(require.resolve),

    plugins: [
        'jsx-a11y',
        'react',
    ],

    parserOptions: {
        jsx: true,
    },

    rules: {
        'class-methods-use-this': [ 'error', { exceptMethods: [ 'render', 'getInitialState', 'getDefaultProps', 'getChildContext', 'componentWillMount', 'componentDidMount', 'componentWillReceiveProps', 'shouldComponentUpdate', 'componentWillUpdate', 'componentDidUpdate', 'componentWillUnmount' ] } ],
        'jsx-a11y/accessible-emoji': 'error',
        'jsx-a11y/alt-text': [ 'error', { elements: [ 'img', 'object', 'area', 'input[type="image"]' ], img: [], object: [], area: [], 'input[type="image"]': [] } ],
        'jsx-a11y/anchor-has-content': [ 'error', { components: [ '' ] } ],
        'jsx-a11y/anchor-is-valid': [ 'off', { components: [ 'Link' ], specialLink: [], aspects: [ 'noHref', 'invalidHref', 'preferButton' ] } ],
        'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
        'jsx-a11y/aria-props': 'error',
        'jsx-a11y/aria-proptypes': 'error',
        'jsx-a11y/aria-role': [ 'error', { ignoreNonDom: false } ],
        'jsx-a11y/aria-unsupported-elements': 'error',
        'jsx-a11y/click-events-have-key-events': 'off',
        'jsx-a11y/heading-has-content': [ 'error', { components: [ '' ] } ],
        'jsx-a11y/href-no-hash': [ 'error', { components: [ 'a' ] } ],
        'jsx-a11y/html-has-lang': 'error',
        'jsx-a11y/iframe-has-title': 'error',
        'jsx-a11y/img-redundant-alt': 'error',
        'jsx-a11y/interactive-supports-focus': 'error',
        'jsx-a11y/label-has-for': [ 'error', { components: [ 'label' ] } ],
        'jsx-a11y/lang': 'error',
        'jsx-a11y/media-has-caption': [ 'error', { audio: [], video: [], track: [] } ],
        'jsx-a11y/mouse-events-have-key-events': 'off',
        'jsx-a11y/no-access-key': 'error',
        'jsx-a11y/no-autofocus': [ 'error', { ignoreNonDOM: true } ],
        'jsx-a11y/no-distracting-elements': [ 'error', { elements: [ 'marquee', 'blink' ] } ],
        'jsx-a11y/no-interactive-element-to-noninteractive-role': [ 'error', { tr: [ 'none', 'presentation' ] } ],
        'jsx-a11y/no-noninteractive-element-interactions': [ 'error', { handlers: [ 'onClick', 'onMouseDown', 'onMouseUp', 'onKeyPress', 'onKeyDown', 'onKeyUp' ] } ],
        'jsx-a11y/no-noninteractive-element-to-interactive-role': [ 'error', { ul: [ 'listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid' ], ol: [ 'listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid' ], li: [ 'menuitem', 'option', 'row', 'tab', 'treeitem' ], table: [ 'grid' ], td: [ 'gridcell' ] } ],
        'jsx-a11y/no-noninteractive-tabindex': [ 'error', { tags: [], roles: [ 'tabpanel' ] } ],
        'jsx-a11y/no-onchange': 'off',
        'jsx-a11y/no-redundant-roles': 'error',
        'jsx-a11y/no-static-element-interactions': [ 'error', { handlers: [ 'onClick', 'onMouseDown', 'onMouseUp', 'onKeyPress', 'onKeyDown', 'onKeyUp' ] } ],
        'jsx-a11y/role-has-required-aria-props': 'error',
        'jsx-a11y/role-supports-aria-props': 'error',
        'jsx-a11y/scope': 'error',
        'jsx-a11y/tabindex-no-positive': 'error',
        'jsx-quotes': [ 'error', 'prefer-double' ],
        'react/boolean-prop-naming': [ 'off', { propTypeNames: [ 'bool', 'mutuallyExclusiveTrueProps' ], rule: '^(is|has)[A-Z]([A-Za-z0-9]?)+' } ],
        'react/default-props-match-prop-types': [ 'off', { allowRequiredDefaults: false } ],
        'react/display-name': [ 'off', { ignoreTranspilerName: false } ],
        'react/forbid-component-props': [ 'off', { forbid: [] } ],
        'react/forbid-elements': [ 'off', { forbid: [] } ],
        'react/forbid-foreign-prop-types': 'off',
        'react/forbid-prop-types': [ 'error', { forbid: [ 'any', 'array', 'object' ] } ],
        'react/jsx-boolean-value': [ 'error', 'never', { always: [] } ],
        'react/jsx-closing-bracket-location': [ 'error', 'line-aligned' ],
        'react/jsx-closing-tag-location': 'error',
        'react/jsx-curly-spacing': [ 'error', 'never', { allowMultiline: true } ],
        'react/jsx-equals-spacing': [ 'error', 'never' ],
        'react/jsx-filename-extension': [ 'error', { extensions: [ '.jsx' ] } ],
        'react/jsx-first-prop-new-line': [ 'error', 'multiline-multiprop' ],
        'react/jsx-handler-names': [ 'off', { eventHandlerPrefix: 'handle', eventHandlerPropPrefix: 'on' } ],
        'react/jsx-indent-props': [ 'error', 4 ],
        'react/jsx-indent': [ 'error', 4 ],
        'react/jsx-key': 'off',
        'react/jsx-max-props-per-line': [ 'error', { maximum: 1, when: 'multiline' } ],
        'react/jsx-no-bind': [ 'error', { ignoreRefs: true, allowArrowFunctions: true, allowBind: false } ],
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-duplicate-props': [ 'error', { ignoreCase: true } ],
        'react/jsx-no-literals': [ 'off', { noStrings: true } ],
        'react/jsx-no-target-blank': 'error',
        'react/jsx-no-undef': 'error',
        'react/jsx-pascal-case': [ 'error', { allowAllCaps: true, ignore: [] } ],
        'react/jsx-sort-prop-types': 'off',
        'react/jsx-sort-props': [ 'off', { ignoreCase: true, callbacksLast: false, shorthandFirst: false, shorthandLast: false, noSortAlphabetically: false, reservedFirst: true } ],
        'react/jsx-space-before-closing': [ 'off', 'always' ],
        'react/jsx-tag-spacing': [ 'error', { closingSlash: 'never', beforeSelfClosing: 'always', afterOpening: 'never' } ],
        'react/jsx-uses-react': [ 'error' ],
        'react/jsx-uses-vars': 'error',
        'react/jsx-wrap-multilines': [ 'error', { declaration: true, assignment: true, return: true, arrow: true } ],
        'react/no-array-index-key': 'error',
        'react/no-children-prop': 'error',
        'react/no-danger-with-children': 'error',
        'react/no-danger': 'warn',
        'react/no-deprecated': [ 'error' ],
        'react/no-did-mount-set-state': 'error',
        'react/no-did-update-set-state': 'error',
        'react/no-direct-mutation-state': 'off',
        'react/no-find-dom-node': 'error',
        'react/no-is-mounted': 'error',
        'react/no-multi-comp': [ 'error', { ignoreStateless: true } ],
        'react/no-redundant-should-component-update': 'off',
        'react/no-render-return-value': 'error',
        'react/no-set-state': 'off',
        'react/no-string-refs': 'error',
        'react/no-typos': 'off',
        'react/no-unescaped-entities': 'error',
        'react/no-unknown-property': 'error',
        'react/no-unused-prop-types': [ 'error', { customValidators: [], skipShapeProps: true } ],
        'react/no-unused-state': 'off',
        'react/no-will-update-set-state': 'error',
        'react/prefer-es6-class': [ 'error', 'always' ],
        'react/prefer-stateless-function': [ 'error', { ignorePureComponents: true } ],
        'react/prop-types': [ 'error', { ignore: [], customValidators: [], skipUndeclared: false } ],
        'react/react-in-jsx-scope': 'error',
        'react/require-default-props': 'error',
        'react/require-optimization': [ 'off', { allowDecorators: [] } ],
        'react/require-render-return': 'error',
        'react/self-closing-comp': 'error',
        'react/sort-comp': [ 'error', { order: [ 'static-methods', 'lifecycle', '/^on.+$/', 'getters', 'setters', '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/', 'everything-else', '/^render.+$/', 'render' ] } ],
        'react/sort-prop-types': [ 'off', { ignoreCase: true, callbacksLast: false, requiredFirst: false } ],
        'react/style-prop-object': 'error',
        'react/void-dom-elements-no-children': 'error',
    },
    
    settings: {
        'import/resolver': {
            node: {
                extensions: [ '.js', '.jsx', '.json' ],
            },
        },
        'import/extensions': [
            '.js',
            '.jsx',
        ],
        react: {
            pragma: 'React',
            version: '15.0',
        },
        propWrapperFunctions: [
            'forbidExtraProps', // https://www.npmjs.com/package/airbnb-prop-types
            'exact', // https://www.npmjs.com/package/prop-types-exact
            'Object.freeze', // https://tc39.github.io/ecma262/#sec-object.freeze
        ],
    },
};
